# Generated by Django 4.1.3 on 2024-03-10 11:28

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255, verbose_name='FirstName')),
                ('last_name', models.CharField(max_length=255, verbose_name='LastName')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.CharField(max_length=1023, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Treatments',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('first_name', models.CharField(max_length=255, verbose_name='FirstName')),
                ('last_name', models.CharField(max_length=255, verbose_name='LastName')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('is_deleted', models.BooleanField(default=False)),
                ('salary', models.IntegerField(default=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='core.user')),
            ],
            options={
                'verbose_name_plural': 'Assistants',
            },
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='core.user')),
            ],
            options={
                'verbose_name_plural': 'Doctors',
            },
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='Recommends',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('days', models.IntegerField(verbose_name='Days')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient', verbose_name='Patient')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.treatment', verbose_name='TreatmentID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctor', verbose_name='Doctor')),
            ],
            options={
                'verbose_name_plural': 'Recommandations',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='assistants',
            field=models.ManyToManyField(to='core.assistant'),
        ),
        migrations.CreateModel(
            name='GeneralManager',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gemeral_managers', to='core.user')),
            ],
            options={
                'verbose_name_plural': 'GeneralManagers',
            },
            bases=('core.user',),
        ),
    ]
