# Generated by Django 4.1.3 on 2024-03-12 19:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Assistants',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255, verbose_name='FirstName')),
                ('last_name', models.CharField(max_length=255, verbose_name='LastName')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('assistants', models.ManyToManyField(to='core.assistant')),
            ],
            options={
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.CharField(max_length=1023, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Treatments',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=31, verbose_name='Username')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('first_name', models.CharField(max_length=255, verbose_name='FirstName')),
                ('last_name', models.CharField(max_length=255, verbose_name='LastName')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('salary', models.IntegerField(default=3000, verbose_name='Salary')),
            ],
        ),
        migrations.CreateModel(
            name='Recommends',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('days', models.IntegerField(verbose_name='Days')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctor', verbose_name='Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient', verbose_name='Patient')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.treatment', verbose_name='TreatmentID')),
            ],
            options={
                'verbose_name_plural': 'Recommandations',
            },
        ),
        migrations.CreateModel(
            name='GeneralManager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gemeral_managers', to='core.user')),
            ],
            options={
                'verbose_name_plural': 'GeneralManagers',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='core.user'),
        ),
        migrations.AddField(
            model_name='assistant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='core.user'),
        ),
    ]
