# Generated by Django 4.1.3 on 2024-03-09 18:34

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('first_name', models.CharField(max_length=255, verbose_name='FirstName')),
                ('last_name', models.CharField(max_length=255, verbose_name='LastName')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('is_deleted', models.BooleanField(default=False)),
                ('salary', models.IntegerField(default=3000)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
